// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: proto/jobboard.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobBoardService_GetJobDetails_FullMethodName  = "/jobboard.JobBoardService/GetJobDetails"
	JobBoardService_GetUserDetails_FullMethodName = "/jobboard.JobBoardService/GetUserDetails"
)

// JobBoardServiceClient is the client API for JobBoardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// JobBoardService provides methods for looking up jobs, companies, and users.
// It is hosted by the job-service and consumed by the notification-service.
type JobBoardServiceClient interface {
	// GetJobDetails returns a job's details including its parent company owner's profile
	// (name and email) in a single request to minimize microservice network roundtrips.
	GetJobDetails(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
	// GetUserDetails returns the basic profile details (name and email) of any registered user.
	GetUserDetails(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
}

type jobBoardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobBoardServiceClient(cc grpc.ClientConnInterface) JobBoardServiceClient {
	return &jobBoardServiceClient{cc}
}

func (c *jobBoardServiceClient) GetJobDetails(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobResponse)
	err := c.cc.Invoke(ctx, JobBoardService_GetJobDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobBoardServiceClient) GetUserDetails(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, JobBoardService_GetUserDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobBoardServiceServer is the server API for JobBoardService service.
// All implementations must embed UnimplementedJobBoardServiceServer
// for forward compatibility.
//
// JobBoardService provides methods for looking up jobs, companies, and users.
// It is hosted by the job-service and consumed by the notification-service.
type JobBoardServiceServer interface {
	// GetJobDetails returns a job's details including its parent company owner's profile
	// (name and email) in a single request to minimize microservice network roundtrips.
	GetJobDetails(context.Context, *GetJobRequest) (*GetJobResponse, error)
	// GetUserDetails returns the basic profile details (name and email) of any registered user.
	GetUserDetails(context.Context, *GetUserRequest) (*GetUserResponse, error)
	mustEmbedUnimplementedJobBoardServiceServer()
}

// UnimplementedJobBoardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobBoardServiceServer struct{}

func (UnimplementedJobBoardServiceServer) GetJobDetails(context.Context, *GetJobRequest) (*GetJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobDetails not implemented")
}
func (UnimplementedJobBoardServiceServer) GetUserDetails(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserDetails not implemented")
}
func (UnimplementedJobBoardServiceServer) mustEmbedUnimplementedJobBoardServiceServer() {}
func (UnimplementedJobBoardServiceServer) testEmbeddedByValue()                         {}

// UnsafeJobBoardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobBoardServiceServer will
// result in compilation errors.
type UnsafeJobBoardServiceServer interface {
	mustEmbedUnimplementedJobBoardServiceServer()
}

func RegisterJobBoardServiceServer(s grpc.ServiceRegistrar, srv JobBoardServiceServer) {
	// If the following call panics, it indicates UnimplementedJobBoardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobBoardService_ServiceDesc, srv)
}

func _JobBoardService_GetJobDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobBoardServiceServer).GetJobDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobBoardService_GetJobDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobBoardServiceServer).GetJobDetails(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobBoardService_GetUserDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobBoardServiceServer).GetUserDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobBoardService_GetUserDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobBoardServiceServer).GetUserDetails(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobBoardService_ServiceDesc is the grpc.ServiceDesc for JobBoardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobBoardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jobboard.JobBoardService",
	HandlerType: (*JobBoardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetJobDetails",
			Handler:    _JobBoardService_GetJobDetails_Handler,
		},
		{
			MethodName: "GetUserDetails",
			Handler:    _JobBoardService_GetUserDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/jobboard.proto",
}
